name: actions-fail

on:
  push:
    branches:
      - master

jobs:
  fail-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check exitting by code 1 fails entire job
        run: |
          echo 'exit 1, no continue-on-error set'
          exit 1

      - name: Next Step 
        run: echo 'next step'
