name: actions-fail

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fail-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin master
      
      - name: Check for changes
        id: check
        run: |
            git fetch origin ${{ github.base_ref }}
            all=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
            matched=$(echo "$all" | grep -c '^.github/')
            total=$(echo "$all" | wc -l)
            if [ "$matched" -eq "$total" ]; then
                echo 'only-gha=true' >> $GITHUB_OUTPUT

      - name: Check 2
        if: ${{ steps.check.outputs.only-gha != 'true' }}
        run: echo 'check 2'

      - name: Next Step 
        run: echo 'next step'
